import { motion } from "framer-motion";
import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Can } from "@/app/guards/Can";
import { ConfirmDialog } from "@/components/feedback/ConfirmDialog";
import { EmptyState } from "@/components/feedback/EmptyState";
import { ErrorState } from "@/components/feedback/ErrorState";
import { LoadingState } from "@/components/feedback/LoadingState";
import { PageContainer } from "@/components/layout/PageContainer";
import { PageHeader } from "@/components/layout/PageHeader";
import { DataTable, type DataTableColumn } from "@/components/tables/DataTable";
import { Button } from "@/components/ui/Button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";
import { MaintenancePriorityBadge, MaintenanceStatusBadge } from "@/components/ui/StatusBadge";
import { useVendor, useVendorMaintenance, useVendorMutations } from "@/features/vendors/useVendors";
import { formatCurrency } from "@/lib/format";
import { pageMotion } from "@/lib/motion";
import type { MaintenanceOut } from "@/types/resources";
function DetailItem({ label, value }: { label: string; value: string | number | null | undefined }) { return <div className="rounded-xl border border-border bg-muted/30 px-4 py-3"><p className="text-meta">{label}</p><p className="mt-1 font-medium text-foreground">{value ?? "—"}</p></div>; }
export function VendorDetailsPage() { const { id } = useParams(); const navigate = useNavigate(); const vendorId = id ? Number(id) : undefined; const vendorQuery = useVendor(vendorId); const jobsQuery = useVendorMaintenance(vendorId); const { deleteMutation } = useVendorMutations(); const [deleteOpen, setDeleteOpen] = useState(false); const columns: Array<DataTableColumn<MaintenanceOut>> = [{ id: "issue", header: "البلاغ", cell: (row) => row.issue_type }, { id: "priority", header: "الأولوية", cell: (row) => row.priority ? <MaintenancePriorityBadge priority={row.priority} /> : "—" }, { id: "status", header: "الحالة", cell: (row) => <MaintenanceStatusBadge status={row.status} /> }, { id: "cost", header: "التكلفة", numeric: true, cell: (row) => formatCurrency(row.cost) }]; if (vendorQuery.isPending) return <LoadingState label="جاري تحميل المورد" />; if (vendorQuery.isError || !vendorQuery.data) return <ErrorState title="تعذر تحميل المورد" description="لم نتمكن من تحميل تفاصيل المورد." onRetry={() => void vendorQuery.refetch()} />; const vendor = vendorQuery.data; return <motion.div {...pageMotion}><PageContainer><PageHeader eyebrow="الموردون" title={vendor.name} description="بيانات المورد وبلاغات الصيانة المرتبطة به." actions={<div className="flex flex-wrap gap-2"><Can permission="vendors.update"><Button asChild className="rounded-full" variant="outline"><Link to={`/vendors/${vendor.id}/edit`}>تعديل</Link></Button></Can><Can permission="vendors.delete"><Button className="rounded-full" variant="destructive" onClick={() => setDeleteOpen(true)}>حذف</Button></Can></div>} /><Card><CardHeader><CardTitle>بيانات المورد</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2"><DetailItem label="الهاتف" value={vendor.phone} /><DetailItem label="البريد الإلكتروني" value={vendor.email} /><DetailItem label="الخدمات المقدمة" value={vendor.services_provided} /><DetailItem label="ملاحظات" value={vendor.notes} /></div></CardContent></Card><section className="space-y-3"><h2 className="text-section text-foreground">بلاغات المورد</h2>{jobsQuery.isError ? <ErrorState compact title="تعذر تحميل بلاغات المورد" description="يمكن متابعة بيانات المورد بدون هذا القسم." onRetry={() => void jobsQuery.refetch()} /> : <DataTable columns={columns} data={jobsQuery.data ?? []} getRowId={(row) => row.id} loading={jobsQuery.isPending} emptyTitle="لا توجد بلاغات" emptyDescription="لا توجد بلاغات صيانة مرتبطة بهذا المورد." emptyAction={<EmptyState compact title="" />} actions={(row) => <Button asChild className="rounded-full" size="sm" variant="ghost"><Link to={`/maintenance/${row.id}`}>عرض</Link></Button>} />}</section><ConfirmDialog open={deleteOpen} title="حذف المورد" description="سيتم حذف المورد عبر DELETE /vendors/{vendor_id}." confirmLabel="حذف المورد" isLoading={deleteMutation.isPending} onOpenChange={setDeleteOpen} onConfirm={() => void deleteMutation.mutateAsync(vendor.id).then(() => navigate("/vendors"))} /></PageContainer></motion.div>; }
