import type { ReportKind } from "@/types/domain";

export const reportKinds = [
  "collections",
  "outstanding",
  "property-performance",
  "contract-expiries",
  "occupancy",
  "maintenance-costs",
  "owners",
  "tenant-payments",
] as const satisfies readonly ReportKind[];

type ReportConfig = {
  title: string;
  shortTitle: string;
  description: string;
  group: "التحصيل والمالية" | "العقود" | "التشغيل" | "الإدارة";
  columns: string[];
  primaryKpi: string;
  secondaryKpi?: string;
  filters: Array<"date" | "property" | "tenant" | "owner" | "vendor" | "status" | "sort">;
  empty: string;
};

export const reportConfig: Record<ReportKind, ReportConfig> = {
  collections: {
    title: "تقرير تحصيل الإيجارات",
    shortTitle: "تحصيل الإيجارات",
    description: "متابعة المستحقات والتحصيل والمتبقي على مستوى العقود والمستأجرين والعقارات.",
    group: "التحصيل والمالية",
    columns: ["tenant_name", "property_name", "unit_number", "due_date", "amount_due", "amount_paid", "balance", "paid_date", "status"],
    primaryKpi: "total_collected",
    secondaryKpi: "collection_rate",
    filters: ["date", "property", "tenant", "status"],
    empty: "لا توجد استحقاقات ضمن الفترة والفلاتر المحددة.",
  },
  outstanding: {
    title: "تقرير الدفعات المتأخرة",
    shortTitle: "الدفعات المتأخرة",
    description: "معرفة من عليه مبالغ متأخرة، وقيمة المتبقي ومدة التأخير.",
    group: "التحصيل والمالية",
    columns: ["tenant_name", "property_name", "unit_number", "due_date", "amount_due", "amount_paid", "balance", "days_overdue", "status"],
    primaryKpi: "total_outstanding",
    secondaryKpi: "affected_tenants",
    filters: ["date", "property", "tenant", "status", "sort"],
    empty: "لا توجد دفعات متأخرة ضمن الفترة المحددة.",
  },
  "property-performance": {
    title: "تقرير أداء العقارات",
    shortTitle: "أداء العقارات",
    description: "مقارنة الإشغال والتحصيل والمتبقي وتكلفة الصيانة لكل عقار.",
    group: "التحصيل والمالية",
    columns: ["property_name", "owner_name", "total_units", "rented_units", "available_units", "occupancy_rate", "amount_paid", "balance", "maintenance_cost", "net_collections_after_maintenance"],
    primaryKpi: "total_collected",
    secondaryKpi: "total_maintenance_cost",
    filters: ["date", "property", "owner"],
    empty: "لا توجد عقارات مطابقة للفلاتر المحددة.",
  },
  "contract-expiries": {
    title: "تقرير انتهاء العقود",
    shortTitle: "العقود القريبة من الانتهاء",
    description: "معرفة العقود التي تنتهي، للمستأجرين والوحدات والعقارات المعنية.",
    group: "العقود",
    columns: ["tenant_name", "property_name", "unit_number", "start_date", "end_date", "rent_value", "days_remaining", "status"],
    primaryKpi: "contract_count",
    secondaryKpi: "within_30_days",
    filters: ["date", "property", "tenant", "status"],
    empty: "لا توجد عقود تنتهي خلال الفترة المحددة.",
  },
  occupancy: {
    title: "تقرير الإشغال والشغور",
    shortTitle: "الإشغال والشغور",
    description: "عرض الوحدات المؤجرة والشاغرة ونسبة الإشغال على مستوى العقارات.",
    group: "التشغيل",
    columns: ["property_name", "owner_name", "total_units", "rented_units", "available_units", "occupancy_rate"],
    primaryKpi: "occupancy_rate",
    secondaryKpi: "available_units",
    filters: ["property", "owner"],
    empty: "لا توجد عقارات أو وحدات مطابقة للفلاتر المحددة.",
  },
  "maintenance-costs": {
    title: "تقرير تكاليف الصيانة",
    shortTitle: "تكاليف الصيانة",
    description: "تفصيل أين صُرفت تكاليف الصيانة، وما الطلب والوحدة والمورد الذي نفذ العمل.",
    group: "التشغيل",
    columns: ["created_at", "property_name", "unit_number", "issue_type", "priority", "vendor_name", "cost", "status", "execution_date"],
    primaryKpi: "total_cost",
    secondaryKpi: "request_count",
    filters: ["date", "property", "vendor", "status"],
    empty: "لا توجد طلبات صيانة مطابقة للفترة والفلاتر المحددة.",
  },
  owners: {
    title: "تقرير الملاك",
    shortTitle: "تقارير الملاك",
    description: "رؤية محفظة كل مالك ووحداته وتحصيله والمبالغ المتبقية وتكلفة الصيانة.",
    group: "الإدارة",
    columns: ["owner_name", "property_count", "total_units", "rented_units", "amount_paid", "balance", "maintenance_cost"],
    primaryKpi: "total_collected",
    secondaryKpi: "owner_count",
    filters: ["date", "owner"],
    empty: "لا توجد بيانات ملاك مطابقة للفلاتر المحددة.",
  },
  "tenant-payments": {
    title: "سجل دفعات المستأجرين",
    shortTitle: "سجل المستأجرين",
    description: "ملخص المستحق والمدفوع والمتبقي وآخر دفعة لكل عقد ومستأجر.",
    group: "الإدارة",
    columns: ["tenant_name", "property_name", "unit_number", "amount_due", "amount_paid", "balance", "last_payment_date"],
    primaryKpi: "total_paid",
    secondaryKpi: "total_outstanding",
    filters: ["date", "property", "tenant", "status"],
    empty: "لا توجد دفعات مستأجرين مطابقة للفلاتر المحددة.",
  },
};

export const fieldLabels: Record<string, string> = {
  payment_count: "عدد الدفعات",
  total_due: "إجمالي المستحق",
  total_collected: "إجمالي المحصل",
  total_paid: "إجمالي المدفوع",
  total_outstanding: "إجمالي المتبقي",
  total_discount: "إجمالي الخصومات",
  total_penalty: "إجمالي الغرامات",
  collection_rate: "نسبة التحصيل",
  overdue_count: "دفعات متأخرة",
  affected_tenants: "مستأجرون متأثرون",
  contract_count: "عدد العقود",
  total_rent_value: "إجمالي قيمة العقود",
  within_30_days: "خلال 30 يومًا",
  within_60_days: "خلال 60 يومًا",
  within_90_days: "خلال 90 يومًا",
  request_count: "عدد الطلبات",
  completed_count: "طلبات مكتملة",
  open_count: "طلبات مفتوحة",
  total_cost: "إجمالي التكلفة",
  average_completed_cost: "متوسط تكلفة الطلب المكتمل",
  total_maintenance_cost: "تكلفة الصيانة",
  property_count: "عدد العقارات",
  owner_count: "عدد الملاك",
  tenant_count: "عدد المستأجرين",
  total_units: "إجمالي الوحدات",
  rented_units: "الوحدات المؤجرة",
  available_units: "الوحدات الشاغرة",
  occupancy_rate: "نسبة الإشغال",
  aging_1_30: "1–30 يوم",
  aging_31_60: "31–60 يوم",
  aging_61_90: "61–90 يوم",
  aging_90_plus: "أكثر من 90 يوم",
  property_name: "العقار",
  unit_number: "الوحدة",
  tenant_name: "المستأجر",
  owner_name: "المالك",
  vendor_name: "المورد / الفني",
  due_date: "تاريخ الاستحقاق",
  paid_date: "آخر دفعة",
  last_payment_date: "آخر دفعة",
  created_at: "تاريخ الطلب",
  execution_date: "تاريخ الإنجاز",
  start_date: "بداية العقد",
  end_date: "نهاية العقد",
  amount_due: "المستحق",
  amount_paid: "المدفوع",
  balance: "المتبقي",
  rent_value: "قيمة العقد",
  cost: "التكلفة",
  maintenance_cost: "تكلفة الصيانة",
  net_collections_after_maintenance: "صافي التحصيل بعد الصيانة",
  days_overdue: "أيام التأخير",
  days_remaining: "الأيام المتبقية",
  status: "الحالة",
  priority: "الأولوية",
  issue_type: "نوع الصيانة",
  description: "وصف الطلب",
  receipt_number: "رقم الإيصال",
};

export function isReportKind(value: string | undefined): value is ReportKind {
  return Boolean(value && reportKinds.includes(value as ReportKind));
}
